config/routes.rb
Rails.application.routes.draw do
  get 'pages/about'

  get 'pages/contact'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwitterFeed</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

</head>

<body>

<nav>
  <div class="nav-wrapper">
    <a href="#!" class="brand-logo">Twitter</a>
    <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
    <ul class="right hide-on-med-and-down">
      <li><a href="#"> <i class ="material-icons">view_list</i></a></li>
      <li><a href="<%= pages_about_path %>"><i class="material-icons">perm_identity</i></a></li>
      <li><a href="<%= pages_contact_path %>"><i class="material-icons">room</i></a></li>
    </ul>
    <ul class="side-nav" id="mobile-demo">
      <li><a href="#"><i class ="material-icons">view_list</i></a></li>
      <li><a href="<%= pages_about_path %>"><i class="mdi-action-perm-identity"></i></a></li>
      <li><a href="<%= pages_contact_path %>"><i class="mdi-maps-place"></i></a></li>
    </ul>
  </div>
</nav>


<div class="row">
  <div class="col m10 offset-m1">
    <%= yield %>
  </div>
</div>

<script>
    $(".button-collapse").sideNav();
</script>

</body>
</html>

app/views/pages/about.html.erb
<div class="container">

  <h3> About Me</h3>

  <div class="card z-depth-3">
    <div class = "card-content white-text">
      <div class="row">

        <div class="col m6">
          <a class="twitter-timeline" href="https://twitter.com/TwitterDev/timelines/539487832448843776?ref_src=twsrc%5Etfw">National Park Tweets - Curated tweets by TwitterDev</a>
          <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
        </div>

        <div class="col m6">
          <div class="card-panel grey lighten-5 z-depth-1">
            <div class="row valign-wrapper">
              <div class="col m3">
                <%= image_tag "avatar.jpg", class: "circle responsive-img" %>
              </div>
              <div class="col m9">
                  <span class="black-text">
                    I am Asfandyar Ashraf Malik. You are very lucky. You got to meet me today
                  </span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/contact.html.erb
<h3>Contact</h3>

<div class="card z-depth-3">
  <div class="card-content">
    <p>Do you wanna talk? Find me on the map and we can have some drinks</p>
    <br/>
    <div id="map-canvas"></div>
  </div>
</div>

<style>
  #map-canvas {
    width: 100%;
    height: 400px;
  }
</style>

<script src="https://maps.googleapis.com/maps/api/js"></script>

<script>
    function initialize() {
        var mapCanvas = document.getElementById('map-canvas');
        var mapOptions = {
            center: new google.maps.LatLng(53.551086, 9.993682),
            zoom: 14,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        }
        var map = new google.maps.Map(mapCanvas, mapOptions);
        var marker = new google.maps.Marker({
            position: new google.maps.LatLng(53.551086, 9.993682),
            title: "Here is Melbourne!"
        });
        marker.setMap(map);
    }
    google.maps.event.addDomListener(window, 'load', initialize);
</script>